services:
  comment_publisher:
    build: .
    env_file:
      - .env
    # ports:
    #   - "${PORT}:${PORT}"  # Exposes the container port (if you need direct access)
    deploy:
      replicas: 3
    networks:
      - live_comments_network
    labels:
      - "logging=promtail"
      - "service=comment_publisher"

networks:
  live_comments_network:
    external: true
    name: live_comments_network
